name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [ubuntu, macos, windows]
        include:
          - build: Ubuntu
            os: ubuntu-latest
            toolchain: 1.49.0
          - build: macOS
            os: macos-latest
            toolchain: 1.49.0
          - build: Windows
            os: windows-latest
            toolchain: 1.49.0
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust (rustup)
        run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
          rustup component add clippy
      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update -qq
          sudo apt install -y libgl-dev xorg-dev
      - name: Check warnings
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test --verbose

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust (rustup)
        run: |
          rustup update 1.49.0
          rustup default 1.49.0
          rustup component add rustfmt
      - name: Check format
        run: cargo fmt -- --check
